In [1]:
import numpy as np

In [2]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,0,0,1]]).T
X.shape,Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

In [4]:
def derivativesSig(z):
    return sig(z)*(1-sig(z))

In [5]:
#one hidden layer weights
wh=2*np.random.random((2,2))-1
bh=2*np.random.random((1,2))-1
wo=2*np.random.random((2,1))-1
bo=2*np.random.random((1,1))-1
lr=0.1

In [ ]:
#forward propagation without any hidden layer
'''for iter in range(10000):
    output0=X
    output=sig(np.dot(output0,weights)+bias)
    first_term=output-Y
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term=derivativesSig(input_for_last_layer)
    first_two=first_term*second_term
    first_two.shape
    
    changes=np.dot(output0.T,first_two)
    weights = weights-lr*changes
    bias_change=np.sum(first_two)
    bias=bias-lr*bias_change
output=sig(np.dot(X,weights)+bias)
weights,bias,output'''

In [14]:
#forward propagation with one hidden layer
for iter in range(1000):
    output0=X
    inputHidden=np.dot(output0,wh)+bh
    outputHidden=sig(inputHidden)
    inputForOutputLayer=np.dot(outputHidden,wo)+bo
    output=sig(inputForOutputLayer)
    
    first_term_output_layer=output-Y
    second_term_output_layer=derivativesSig(inputForOutputLayer)
    first_two_output_layer=first_term_output_layer*second_term_output_layer
    
    first_term_hidden_layer=np.dot(first_two_output_layer,wo.T)
    second_term_hidden_layer=derivativesSig(inputHidden)
    first_two_hidden_layer=first_term_hidden_layer*second_term_hidden_layer
    
    changes_output=np.dot(outputHidden.T,first_two_output_layer)
    changes_output_bias=np.sum(first_two_output_layer,axis=0,keepdims=True)
    changes_hidden=np.dot(output0.T,first_two_hidden_layer)
    changes_hidden_bias=np.sum(first_two_hidden_layer,axis=0,keepdims=True)
    
    wo=wo-lr*changes_output
    bo=bo-lr*changes_output_bias
    
    wh=wh-lr*changes_hidden
    bh=bh-lr*changes_hidden_bias
    
output0=X
inputHidden=np.dot(output0,wh)+bh
outputHidden=sig(inputHidden)
inputForOutputLayer=np.dot(outputHidden,wo)+bo
output=sig(inputForOutputLayer)
output,wh,bh,wo,bo

(array([[0.00433669],
        [0.04237587],
        [0.04988611],
        [0.92918229]]),
 array([[-3.07655296,  1.73466354],
        [-3.49235504,  0.63877698]]),
 array([[ 4.54473187, -0.58305763]]),
 array([[-7.52854468],
        [ 2.88639158]]),
 array([[0.9791224]]))