In [19]:
import numpy as np

In [20]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,0,0,1]]).T
X.shape,Y.shape

((4, 2), (4, 1))

In [21]:
def sig(z):
    return 1/(1+np.exp(-z))

In [22]:
def derivativesSig(z):
    return sig(z)*(1-sig(z))

In [41]:
#will multiply by 2 so that range becomes 0 to 2 and will subtract
#no hidden layers
weights=2*np.random.random((2,1)) - 1
bias=2*np.random.random(1) - 1
lr=0.1
weights, bias

(array([[-0.94513109],
        [ 0.99048106]]),
 array([0.7565769]))

In [36]:
#forward propagation without any hidden layer
output0=X
#actual output
output=sig(np.dot(output0,weights)+bias)
output

array([[0.51727158],
       [0.73272544],
       [0.34181461],
       [0.57056647]])

In [39]:
#implementing using formula
for iter in range(10000):
    output0=X
    output=sig(np.dot(output0,weights)+bias)
    first_term=output-Y
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term=derivativesSig(input_for_last_layer)
    first_two=first_term*second_term
    first_two.shape
    
    changes=np.array([[0.0],[0.0]])
    
    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0]*output0[j][i]
    weights = weights-lr*changes
    bias_change=0.0
    for j in range(4):
        bias_change+=first_two[j][0]*i
    bias=bias-lr*bias_change
output=sig(np.dot(X,weights)+bias)
weights,bias,output

(array([[5.47824061],
        [5.4782406 ]]),
 array([-8.31005829]),
 array([[2.45969186e-04],
        [5.56288297e-02],
        [5.56288302e-02],
        [9.33790177e-01]]))

In [42]:
#removing the for loop and optimizing the code
#forward propagation without any hidden layer
for iter in range(10000):
    output0=X
    output=sig(np.dot(output0,weights)+bias)
    first_term=output-Y
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term=derivativesSig(input_for_last_layer)
    first_two=first_term*second_term
    first_two.shape
    
    changes=np.dot(output0.T,first_two)
    weights = weights-lr*changes
    bias_change=np.sum(first_two)
    bias=bias-lr*bias_change
output=sig(np.dot(X,weights)+bias)
weights,bias,output

(array([[5.47269392],
        [5.47269395]]),
 array([-8.30176298]),
 array([[2.48017554e-04],
        [5.57734052e-02],
        [5.57734033e-02],
        [9.33616975e-01]]))

In [25]:
#hidden layers
wh=2*np.random.random((2,2))-1
bh=2*np.random.random((1,2))-1
wo=2*np.random.random((2,1))-1
bo=2*np.random.random((1,1))-1

In [26]:
output0=X
outputHidden=sig(np.dot(output0,wh)+bh)
output=sig(np.dot(outputHidden,wo)+bo)
output

array([[0.40573502],
       [0.39839406],
       [0.38683678],
       [0.37679794]])