In [41]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
training=pd.read_csv('0000000000002429_training_titanic_x_y_train.csv').copy()
testing=pd.read_csv('0000000000002429_test_titanic_x_test.csv').copy()

In [43]:
training

Pclass                                            Name     Sex   Age  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1         3               Williams, Mr. Howard Hugh "Harry"    male   0.0   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4         3                          Sutehall, Mr. Henry Jr    male  25.0   
..      ...                                             ...     ...   ...   
663       2                             Ilett, Miss. Bertha  female  17.0   
664       3                        Morrow, Mr. Thomas Rowan    male   0.0   
665       3                                   Bing, Mr. Lee    male  32.0   
666       3                     Strandberg, Miss. Ida Sofia  female  22.0   
667       3                  Murphy, Miss. Katherine "Kate"  female   0.0   

     SibSp  Parch           Ticket     Fare Cabin Embarked  Survived  
0        1      0           228414  26.0000   NaN        S         1  
1        0      0         A/5 2466   8.0500   NaN        S         0  
2        0      0           250655  26.0000   NaN        S         0  
3        0      4           349909  21.0750   NaN        S         0  
4        0      0  SOTON/OQ 392076   7.0500   NaN        S         0  
..     ...    ...              ...      ...   ...      ...       ...  
663      0      0       SO/C 14885  10.5000   NaN        S         1  
664      0      0           372622   7.7500   NaN        Q         0  
665      0      0             1601  56.4958   NaN        S         1  
666      0      0             7553   9.8375   NaN        S         0  
667      1      0           367230  15.5000   NaN        Q         1  

[668 rows x 11 columns]

In [44]:
training['Ticket'].value_counts()

3101295         6
347082          6
1601            6
CA. 2343        5
S.O.C. 14879    5
               ..
PC 17596        1
113773          1
PC 17599        1
236171          1
223596          1
Name: Ticket, Length: 524, dtype: int64

In [45]:
title_training=[]
for i in training['Name']:
    title_training.append(i.split(',')[1].split('.')[0].strip())
title_training=np.array(title_training)
title_training[title_training=='Master']=0
title_training[title_training=='Miss']=1
title_training[title_training=='Mr']=2
title_training[title_training=='Mrs']=3
title_training[(title_training!='0')&(title_training!='1')&(title_training!='2')&(title_training!='3')]=4
title_training=np.array(title_training, dtype='int')
title_training
#'Master', 'Miss', 'Mr', 'Mrs'

array([3, 2, 2, 3, 2, 2, 3, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 4, 3,
       3, 2, 3, 1, 2, 2, 2, 2, 3, 2, 2, 1, 4, 2, 0, 0, 2, 2, 2, 2, 3, 1,
       2, 2, 2, 2, 3, 2, 1, 0, 2, 3, 2, 1, 2, 2, 2, 3, 2, 2, 2, 3, 1, 3,
       2, 2, 2, 2, 3, 2, 2, 2, 2, 1, 1, 4, 3, 3, 3, 2, 3, 2, 1, 2, 2, 2,
       2, 2, 3, 3, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2,
       1, 3, 2, 1, 2, 2, 2, 2, 1, 1, 3, 4, 1, 1, 1, 2, 2, 2, 2, 3, 2, 1,
       2, 2, 2, 3, 2, 2, 2, 4, 2, 3, 2, 2, 2, 2, 3, 2, 1, 1, 3, 2, 3, 1,
       3, 2, 3, 2, 1, 3, 3, 1, 2, 2, 2, 4, 2, 2, 2, 0, 2, 4, 3, 2, 4, 1,
       3, 2, 2, 2, 2, 1, 3, 2, 3, 0, 2, 1, 3, 2, 2, 1, 1, 2, 2, 2, 2, 2,
       2, 2, 1, 4, 1, 2, 1, 2, 3, 2, 2, 0, 3, 3, 1, 2, 1, 2, 2, 0, 1, 1,
       1, 2, 3, 2, 2, 2, 3, 2, 3, 2, 2, 0, 3, 2, 2, 2, 2, 3, 2, 1, 2, 2,
       2, 3, 2, 2, 1, 3, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 3, 2, 2, 4,
       2, 2, 3, 2, 2, 2, 0, 0, 2, 3, 1, 2, 2, 0, 2, 2, 2, 3, 1, 2, 2, 1,
       1, 2, 2, 2, 1, 2, 2, 1, 3, 1, 0, 2, 2, 1, 2,

In [46]:
testing

Pclass                                               Name     Sex   Age  \
0         2                     Davies, Master. John Morgan Jr    male   8.0   
1         1                        Leader, Dr. Alice (Farnham)  female  49.0   
2         3                            Kilgannon, Mr. Thomas J    male   NaN   
3         2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4         1                          McGough, Mr. James Robert    male  36.0   
..      ...                                                ...     ...   ...   
218       3                        Lindqvist, Mr. Eino William    male  20.0   
219       1                  Butt, Major. Archibald Willingham    male  45.0   
220       1  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0   
221       3                   Holm, Mr. John Fredrik Alexander    male  43.0   
222       2           Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5   

     SibSp  Parch             Ticket      Fare Cabin Embarked  
0        1      1         C.A. 33112   36.7500   NaN        S  
1        0      0              17465   25.9292   D17        S  
2        0      0              36865    7.7375   NaN        Q  
3        2      1             243847   27.0000   NaN        S  
4        0      0           PC 17473   26.2875   E25        S  
..     ...    ...                ...       ...   ...      ...  
218      1      0  STON/O 2. 3101285    7.9250   NaN        S  
219      0      0             113050   26.5500   B38        S  
220      1      0           PC 17758  108.9000   C65        C  
221      0      0             C 7075    6.4500   NaN        S  
222      0      2             230080   26.0000    F2        S  

[223 rows x 10 columns]

In [47]:
title_testing=[]
for i in testing['Name']:
    title_testing.append(i.split(',')[1].split('.')[0].strip())
title_testing=np.array(title_testing)
title_testing[title_testing=='Master']=0
title_testing[title_testing=='Miss']=1
title_testing[title_testing=='Mr']=2
title_testing[title_testing=='Mrs']=3
title_testing[(title_testing!='0')&(title_testing!='1')&(title_testing!='2')&(title_testing!='3')]=4
title_testing=np.array(title_testing, dtype='int')
title_testing
#'Master', 'Miss', 'Mr', 'Mrs'

array([0, 4, 2, 3, 2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 0, 2, 1, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 3, 1, 2, 2, 2, 1, 2, 4, 2,
       1, 0, 2, 1, 2, 2, 2, 1, 3, 1, 2, 2, 0, 2, 2, 2, 2, 4, 3, 1, 3, 2,
       2, 4, 1, 4, 2, 2, 2, 2, 2, 3, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 0, 1, 1, 2, 1, 0, 1, 1, 4, 4, 2, 2,
       2, 3, 3, 2, 3, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 3, 1, 2, 1, 2,
       1, 2, 2, 1, 2, 0, 2, 1, 3, 1, 1, 2, 2, 2, 3, 1, 3, 1, 1, 2, 1, 2,
       2, 2, 2, 1, 2, 2, 0, 1, 3, 2, 3, 2, 1, 2, 2, 2, 3, 2, 2, 1, 1, 1,
       3, 4, 2, 4, 2, 2, 2, 2, 2, 2, 3, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 4,
       3, 2, 2])

In [48]:
training.describe(include='all')

Pclass                   Name   Sex         Age       SibSp  \
count   668.000000                    668   668  668.000000  668.000000   
unique         NaN                    668     2         NaN         NaN   
top            NaN  Stewart, Mr. Albert A  male         NaN         NaN   
freq           NaN                      1   427         NaN         NaN   
mean      2.296407                    NaN   NaN   23.831587    0.528443   
std       0.831638                    NaN   NaN   17.399143    1.080327   
min       1.000000                    NaN   NaN    0.000000    0.000000   
25%       2.000000                    NaN   NaN    6.000000    0.000000   
50%       3.000000                    NaN   NaN   25.000000    0.000000   
75%       3.000000                    NaN   NaN   35.000000    1.000000   
max       3.000000                    NaN   NaN   80.000000    8.000000   

             Parch   Ticket        Fare Cabin Embarked    Survived  
count   668.000000      668  668.000000   154      667  668.000000  
unique         NaN      524         NaN   119        3         NaN  
top            NaN  3101295         NaN    G6        S         NaN  
freq           NaN        6         NaN     4      484         NaN  
mean      0.407186      NaN   32.064552   NaN      NaN    0.402695  
std       0.854695      NaN   45.320835   NaN      NaN    0.490808  
min       0.000000      NaN    0.000000   NaN      NaN    0.000000  
25%       0.000000      NaN    7.925000   NaN      NaN    0.000000  
50%       0.000000      NaN   14.750000   NaN      NaN    0.000000  
75%       0.000000      NaN   31.275000   NaN      NaN    1.000000  
max       6.000000      NaN  512.329200   NaN      NaN    1.000000

In [49]:
testing.describe(include='all')

Pclass                Name   Sex         Age       SibSp  \
count   223.000000                 223   223  178.000000  223.000000   
unique         NaN                 223     2         NaN         NaN   
top            NaN  Maisner, Mr. Simon  male         NaN         NaN   
freq           NaN                   1   150         NaN         NaN   
mean      2.345291                 NaN   NaN   29.694775    0.506726   
std       0.850047                 NaN   NaN   15.398053    1.169700   
min       1.000000                 NaN   NaN    0.420000    0.000000   
25%       2.000000                 NaN   NaN   19.250000    0.000000   
50%       3.000000                 NaN   NaN   27.000000    0.000000   
75%       3.000000                 NaN   NaN   37.750000    1.000000   
max       3.000000                 NaN   NaN   71.000000    8.000000   

             Parch   Ticket        Fare    Cabin Embarked  
count   223.000000      223  223.000000       50      222  
unique         NaN      212         NaN       49        3  
top            NaN  CA 2144         NaN  B58 B60        S  
freq           NaN        3         NaN        2      160  
mean      0.304933      NaN   32.622551      NaN      NaN  
std       0.634108      NaN   61.062047      NaN      NaN  
min       0.000000      NaN    0.000000      NaN      NaN  
25%       0.000000      NaN    7.879200      NaN      NaN  
50%       0.000000      NaN   12.475000      NaN      NaN  
75%       0.000000      NaN   30.035400      NaN      NaN  
max       2.000000      NaN  512.329200      NaN      NaN

In [50]:
tr=training
tr=tr.drop('Name', axis=1)
tr.loc[tr['Sex']=='female', 'Sex']=0
tr.loc[tr['Sex']=='male', 'Sex']=1
tr.loc[tr['Age'].isnull(), 'Age']=tr.loc[tr['Age'].notnull() , 'Age'].median()
tr.loc[tr['Embarked'].isnull(), 'Embarked']='S'
tr.loc[tr['Embarked']=='S', 'Embarked']=1
tr.loc[tr['Embarked']=='C', 'Embarked']=2
tr.loc[tr['Embarked']=='Q', 'Embarked']=3
tr.loc[tr['Cabin'].isnull(), 'Cabin']=0
tr.loc[tr['Cabin']!=0, 'Cabin']=1
tr=tr.drop('Ticket', axis=1)
training_data=tr.values
x=training_data[:, :-1]
y=training_data[:, -1]
x=np.append(x, title_training.reshape(-1, 1), axis=1)
x.shape

(668, 9)

In [51]:
ts=testing
ts=ts.drop('Name', axis=1)
ts.loc[ts['Sex']=='female', 'Sex']=0
ts.loc[ts['Sex']=='male', 'Sex']=1
ts.loc[ts['Age'].isnull(), 'Age']=ts.loc[ts['Age'].notnull() , 'Age'].median()
ts.loc[ts['Embarked'].isnull(), 'Embarked']='S'
ts.loc[ts['Embarked']=='S', 'Embarked']=1
ts.loc[ts['Embarked']=='C', 'Embarked']=2
ts.loc[ts['Embarked']=='Q', 'Embarked']=3
ts.loc[ts['Cabin'].isnull(), 'Cabin']=0
ts.loc[ts['Cabin']!=0, 'Cabin']=1
ts=ts.drop('Ticket', axis=1)
testing_data=ts.values
testing_data=np.append(testing_data, title_testing.reshape(-1, 1), axis=1)
testing_data.shape

(223, 9)

In [52]:
testing_data

array([[2, 1, 8.0, ..., 0, 1, 0],
       [1, 0, 49.0, ..., 1, 1, 4],
       [3, 1, 27.0, ..., 0, 3, 2],
       ...,
       [1, 0, 17.0, ..., 1, 2, 3],
       [3, 1, 43.0, ..., 0, 1, 2],
       [2, 1, 36.5, ..., 1, 1, 2]], dtype=object)

In [53]:
training_data

array([[2, 0, 29.0, ..., 0, 1, 1],
       [3, 1, 0.0, ..., 0, 1, 0],
       [2, 1, 39.0, ..., 0, 1, 0],
       ...,
       [3, 1, 32.0, ..., 0, 1, 1],
       [3, 0, 22.0, ..., 0, 1, 0],
       [3, 0, 0.0, ..., 0, 3, 1]], dtype=object)

In [54]:
clf=LogisticRegression(solver='saga', max_iter=100000, tol=0.00001)
clf.fit(x, y)

ValueError: Unknown label type: 'unknown'

In [40]:
predicted=clf.predict(testing_data)

NotFittedError: This LogisticRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.